// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: classer/v1/classer.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetClassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Week     int64  `protobuf:"varint,1,opt,name=week,proto3" json:"week,omitempty"`               //周几的课表
	StuId    string `protobuf:"bytes,2,opt,name=stu_id,json=stuId,proto3" json:"stu_id,omitempty"` //学号
	Semester string `protobuf:"bytes,3,opt,name=semester,proto3" json:"semester,omitempty"`        // 学期
	Year     string `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`                //学年
}

func (x *GetClassRequest) Reset() {
	*x = GetClassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassRequest) ProtoMessage() {}

func (x *GetClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassRequest.ProtoReflect.Descriptor instead.
func (*GetClassRequest) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{0}
}

func (x *GetClassRequest) GetWeek() int64 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *GetClassRequest) GetStuId() string {
	if x != nil {
		return x.StuId
	}
	return ""
}

func (x *GetClassRequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *GetClassRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type GetClassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classes []*Class `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"` //课表
}

func (x *GetClassResponse) Reset() {
	*x = GetClassResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassResponse) ProtoMessage() {}

func (x *GetClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassResponse.ProtoReflect.Descriptor instead.
func (*GetClassResponse) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{1}
}

func (x *GetClassResponse) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

type AddClassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuId    string  `protobuf:"bytes,1,opt,name=stu_id,json=stuId,proto3" json:"stu_id,omitempty"`          //学号
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         //课程名称
	DurClass string  `protobuf:"bytes,3,opt,name=dur_class,json=durClass,proto3" json:"dur_class,omitempty"` //第几节 '形如 "1-3","1-1"'
	Where    string  `protobuf:"bytes,4,opt,name=where,proto3" json:"where,omitempty"`                       //地点
	Teacher  string  `protobuf:"bytes,5,opt,name=teacher,proto3" json:"teacher,omitempty"`                   //教师
	Weeks    int64   `protobuf:"varint,6,opt,name=weeks,proto3" json:"weeks,omitempty"`                      //哪些周
	Semester string  `protobuf:"bytes,7,opt,name=semester,proto3" json:"semester,omitempty"`                 // 学期
	Year     string  `protobuf:"bytes,8,opt,name=year,proto3" json:"year,omitempty"`                         //学年
	Day      int64   `protobuf:"varint,9,opt,name=day,proto3" json:"day,omitempty"`                          //星期几
	Credit   float64 `protobuf:"fixed64,10,opt,name=credit,proto3" json:"credit,omitempty"`                  //学分
}

func (x *AddClassRequest) Reset() {
	*x = AddClassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClassRequest) ProtoMessage() {}

func (x *AddClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClassRequest.ProtoReflect.Descriptor instead.
func (*AddClassRequest) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{2}
}

func (x *AddClassRequest) GetStuId() string {
	if x != nil {
		return x.StuId
	}
	return ""
}

func (x *AddClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddClassRequest) GetDurClass() string {
	if x != nil {
		return x.DurClass
	}
	return ""
}

func (x *AddClassRequest) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *AddClassRequest) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *AddClassRequest) GetWeeks() int64 {
	if x != nil {
		return x.Weeks
	}
	return 0
}

func (x *AddClassRequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *AddClassRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *AddClassRequest) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *AddClassRequest) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

type AddClassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` //添加的课程ID
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddClassResponse) Reset() {
	*x = AddClassResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClassResponse) ProtoMessage() {}

func (x *AddClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClassResponse.ProtoReflect.Descriptor instead.
func (*AddClassResponse) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{3}
}

func (x *AddClassResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddClassResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteClassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             //课程标识
	StuId    string `protobuf:"bytes,2,opt,name=stuId,proto3" json:"stuId,omitempty"`       //学号
	Year     string `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`         //学年  "2024" 代表"2024-2025学年"
	Semester string `protobuf:"bytes,4,opt,name=semester,proto3" json:"semester,omitempty"` //学期 "1"代表第一学期，"2"代表第二学期，"3"代表第三学期
}

func (x *DeleteClassRequest) Reset() {
	*x = DeleteClassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassRequest) ProtoMessage() {}

func (x *DeleteClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassRequest.ProtoReflect.Descriptor instead.
func (*DeleteClassRequest) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteClassRequest) GetStuId() string {
	if x != nil {
		return x.StuId
	}
	return ""
}

func (x *DeleteClassRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *DeleteClassRequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type DeleteClassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteClassResponse) Reset() {
	*x = DeleteClassResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassResponse) ProtoMessage() {}

func (x *DeleteClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassResponse.ProtoReflect.Descriptor instead.
func (*DeleteClassResponse) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteClassResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClassInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day          int64   `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`                                      //星期几
	Teacher      string  `protobuf:"bytes,2,opt,name=teacher,proto3" json:"teacher,omitempty"`                               //任课教师
	Where        string  `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`                                   //上课地点
	ClassWhen    string  `protobuf:"bytes,4,opt,name=class_when,json=classWhen,proto3" json:"class_when,omitempty"`          //上课是第几节（如1-2,3,4）
	WeekDuration string  `protobuf:"bytes,5,opt,name=week_duration,json=weekDuration,proto3" json:"week_duration,omitempty"` //上课的周数
	Classname    string  `protobuf:"bytes,6,opt,name=classname,proto3" json:"classname,omitempty"`                           //课程名称
	Credit       float64 `protobuf:"fixed64,7,opt,name=credit,proto3" json:"credit,omitempty"`                               //学分
	// bool add=8;//是否为手动添加
	Weeks    int64  `protobuf:"varint,9,opt,name=weeks,proto3" json:"weeks,omitempty"`       //哪些周
	Semester string `protobuf:"bytes,10,opt,name=semester,proto3" json:"semester,omitempty"` //学期 "1"代表第一学期，"2"代表第二学期，"3"代表第三学期
	Year     string `protobuf:"bytes,11,opt,name=year,proto3" json:"year,omitempty"`         //学年  "2024" 代表"2024-2025学年"
	Id       string `protobuf:"bytes,12,opt,name=id,proto3" json:"id,omitempty"`             //课程唯一标识
}

func (x *ClassInfo) Reset() {
	*x = ClassInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassInfo) ProtoMessage() {}

func (x *ClassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassInfo.ProtoReflect.Descriptor instead.
func (*ClassInfo) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{6}
}

func (x *ClassInfo) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *ClassInfo) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *ClassInfo) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *ClassInfo) GetClassWhen() string {
	if x != nil {
		return x.ClassWhen
	}
	return ""
}

func (x *ClassInfo) GetWeekDuration() string {
	if x != nil {
		return x.WeekDuration
	}
	return ""
}

func (x *ClassInfo) GetClassname() string {
	if x != nil {
		return x.Classname
	}
	return ""
}

func (x *ClassInfo) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *ClassInfo) GetWeeks() int64 {
	if x != nil {
		return x.Weeks
	}
	return 0
}

func (x *ClassInfo) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *ClassInfo) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *ClassInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Class struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info     *ClassInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Thisweek bool       `protobuf:"varint,2,opt,name=thisweek,proto3" json:"thisweek,omitempty"` //是否是本周
}

func (x *Class) Reset() {
	*x = Class{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classer_v1_classer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_classer_v1_classer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_classer_v1_classer_proto_rawDescGZIP(), []int{7}
}

func (x *Class) GetInfo() *ClassInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Class) GetThisweek() bool {
	if x != nil {
		return x.Thisweek
	}
	return false
}

var File_classer_v1_classer_proto protoreflect.FileDescriptor

var file_classer_v1_classer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x74, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x75,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x22, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x74, 0x75, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x75, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x75, 0x72, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x77, 0x68, 0x65, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x77, 0x65, 0x65, 0x6b, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x22,
	0x34, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x6a, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x75, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x75, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x27, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x9d, 0x02, 0x0a, 0x09, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x5f, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x57, 0x68, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x65, 0x65,
	0x6b, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x77, 0x65, 0x65, 0x6b, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x05, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x68, 0x69, 0x73, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x74, 0x68, 0x69, 0x73, 0x77, 0x65, 0x65, 0x6b, 0x32, 0xcd, 0x02, 0x0a, 0x07, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x12, 0x78, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x2b, 0x12, 0x29, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x67, 0x65,
	0x74, 0x61, 0x6c, 0x6c, 0x2f, 0x7b, 0x77, 0x65, 0x65, 0x6b, 0x2c, 0x73, 0x74, 0x75, 0x5f, 0x69,
	0x64, 0x2c, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2c, 0x79, 0x65, 0x61, 0x72, 0x7d,
	0x12, 0x5c, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1b, 0x2e, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x3a,
	0x01, 0x2a, 0x22, 0x0a, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x61, 0x64, 0x64, 0x12, 0x6a,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1e, 0x2e,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x19, 0x5a, 0x17, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_classer_v1_classer_proto_rawDescOnce sync.Once
	file_classer_v1_classer_proto_rawDescData = file_classer_v1_classer_proto_rawDesc
)

func file_classer_v1_classer_proto_rawDescGZIP() []byte {
	file_classer_v1_classer_proto_rawDescOnce.Do(func() {
		file_classer_v1_classer_proto_rawDescData = protoimpl.X.CompressGZIP(file_classer_v1_classer_proto_rawDescData)
	})
	return file_classer_v1_classer_proto_rawDescData
}

var file_classer_v1_classer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_classer_v1_classer_proto_goTypes = []interface{}{
	(*GetClassRequest)(nil),     // 0: classer.v1.GetClassRequest
	(*GetClassResponse)(nil),    // 1: classer.v1.GetClassResponse
	(*AddClassRequest)(nil),     // 2: classer.v1.AddClassRequest
	(*AddClassResponse)(nil),    // 3: classer.v1.AddClassResponse
	(*DeleteClassRequest)(nil),  // 4: classer.v1.DeleteClassRequest
	(*DeleteClassResponse)(nil), // 5: classer.v1.DeleteClassResponse
	(*ClassInfo)(nil),           // 6: classer.v1.ClassInfo
	(*Class)(nil),               // 7: classer.v1.Class
}
var file_classer_v1_classer_proto_depIdxs = []int32{
	7, // 0: classer.v1.GetClassResponse.classes:type_name -> classer.v1.Class
	6, // 1: classer.v1.Class.info:type_name -> classer.v1.ClassInfo
	0, // 2: classer.v1.Classer.GetClass:input_type -> classer.v1.GetClassRequest
	2, // 3: classer.v1.Classer.AddClass:input_type -> classer.v1.AddClassRequest
	4, // 4: classer.v1.Classer.DeleteClass:input_type -> classer.v1.DeleteClassRequest
	1, // 5: classer.v1.Classer.GetClass:output_type -> classer.v1.GetClassResponse
	3, // 6: classer.v1.Classer.AddClass:output_type -> classer.v1.AddClassResponse
	5, // 7: classer.v1.Classer.DeleteClass:output_type -> classer.v1.DeleteClassResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_classer_v1_classer_proto_init() }
func file_classer_v1_classer_proto_init() {
	if File_classer_v1_classer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_classer_v1_classer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classer_v1_classer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClassResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classer_v1_classer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddClassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classer_v1_classer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddClassResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classer_v1_classer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classer_v1_classer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClassResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classer_v1_classer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classer_v1_classer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Class); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_classer_v1_classer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classer_v1_classer_proto_goTypes,
		DependencyIndexes: file_classer_v1_classer_proto_depIdxs,
		MessageInfos:      file_classer_v1_classer_proto_msgTypes,
	}.Build()
	File_classer_v1_classer_proto = out.File
	file_classer_v1_classer_proto_rawDesc = nil
	file_classer_v1_classer_proto_goTypes = nil
	file_classer_v1_classer_proto_depIdxs = nil
}
