// Code generated by MockGen. DO NOT EDIT.
// Source: ./classInfo.go

// Package mock_biz is a generated GoMock package.
package mock_biz

import (
	biz "github.com/asynccnu/Muxi_ClassList/internal/biz"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClassInfoDBRepo is a mock of ClassInfoDBRepo interface.
type MockClassInfoDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockClassInfoDBRepoMockRecorder
}

// MockClassInfoDBRepoMockRecorder is the mock recorder for MockClassInfoDBRepo.
type MockClassInfoDBRepoMockRecorder struct {
	mock *MockClassInfoDBRepo
}

// NewMockClassInfoDBRepo creates a new mock instance.
func NewMockClassInfoDBRepo(ctrl *gomock.Controller) *MockClassInfoDBRepo {
	mock := &MockClassInfoDBRepo{ctrl: ctrl}
	mock.recorder = &MockClassInfoDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassInfoDBRepo) EXPECT() *MockClassInfoDBRepoMockRecorder {
	return m.recorder
}

// AddClassInfoToDB mocks base method.
func (m *MockClassInfoDBRepo) AddClassInfoToDB(ctx context.Context, classInfo *biz.ClassInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClassInfoToDB", ctx, classInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClassInfoToDB indicates an expected call of AddClassInfoToDB.
func (mr *MockClassInfoDBRepoMockRecorder) AddClassInfoToDB(ctx, classInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClassInfoToDB", reflect.TypeOf((*MockClassInfoDBRepo)(nil).AddClassInfoToDB), ctx, classInfo)
}

// DeleteClassInfoInDB mocks base method.
func (m *MockClassInfoDBRepo) DeleteClassInfoInDB(ctx context.Context, ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClassInfoInDB", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClassInfoInDB indicates an expected call of DeleteClassInfoInDB.
func (mr *MockClassInfoDBRepoMockRecorder) DeleteClassInfoInDB(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClassInfoInDB", reflect.TypeOf((*MockClassInfoDBRepo)(nil).DeleteClassInfoInDB), ctx, ID)
}

// GetClassInfoFromDB mocks base method.
func (m *MockClassInfoDBRepo) GetClassInfoFromDB(ctx context.Context, ID string) (*biz.ClassInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClassInfoFromDB", ctx, ID)
	ret0, _ := ret[0].(*biz.ClassInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClassInfoFromDB indicates an expected call of GetClassInfoFromDB.
func (mr *MockClassInfoDBRepoMockRecorder) GetClassInfoFromDB(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClassInfoFromDB", reflect.TypeOf((*MockClassInfoDBRepo)(nil).GetClassInfoFromDB), ctx, ID)
}

// SaveClassInfosToDB mocks base method.
func (m *MockClassInfoDBRepo) SaveClassInfosToDB(ctx context.Context, classInfo []*biz.ClassInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveClassInfosToDB", ctx, classInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveClassInfosToDB indicates an expected call of SaveClassInfosToDB.
func (mr *MockClassInfoDBRepoMockRecorder) SaveClassInfosToDB(ctx, classInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveClassInfosToDB", reflect.TypeOf((*MockClassInfoDBRepo)(nil).SaveClassInfosToDB), ctx, classInfo)
}

// MockClassInfoCacheRepo is a mock of ClassInfoCacheRepo interface.
type MockClassInfoCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockClassInfoCacheRepoMockRecorder
}

// MockClassInfoCacheRepoMockRecorder is the mock recorder for MockClassInfoCacheRepo.
type MockClassInfoCacheRepoMockRecorder struct {
	mock *MockClassInfoCacheRepo
}

// NewMockClassInfoCacheRepo creates a new mock instance.
func NewMockClassInfoCacheRepo(ctrl *gomock.Controller) *MockClassInfoCacheRepo {
	mock := &MockClassInfoCacheRepo{ctrl: ctrl}
	mock.recorder = &MockClassInfoCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassInfoCacheRepo) EXPECT() *MockClassInfoCacheRepoMockRecorder {
	return m.recorder
}

// AddClassInfoToCache mocks base method.
func (m *MockClassInfoCacheRepo) AddClassInfoToCache(ctx context.Context, key string, classInfo *biz.ClassInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClassInfoToCache", ctx, key, classInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClassInfoToCache indicates an expected call of AddClassInfoToCache.
func (mr *MockClassInfoCacheRepoMockRecorder) AddClassInfoToCache(ctx, key, classInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClassInfoToCache", reflect.TypeOf((*MockClassInfoCacheRepo)(nil).AddClassInfoToCache), ctx, key, classInfo)
}

// DeleteClassInfoFromCache mocks base method.
func (m *MockClassInfoCacheRepo) DeleteClassInfoFromCache(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClassInfoFromCache", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClassInfoFromCache indicates an expected call of DeleteClassInfoFromCache.
func (mr *MockClassInfoCacheRepoMockRecorder) DeleteClassInfoFromCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClassInfoFromCache", reflect.TypeOf((*MockClassInfoCacheRepo)(nil).DeleteClassInfoFromCache), ctx, key)
}

// GetClassInfoFromCache mocks base method.
func (m *MockClassInfoCacheRepo) GetClassInfoFromCache(ctx context.Context, key string) (*biz.ClassInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClassInfoFromCache", ctx, key)
	ret0, _ := ret[0].(*biz.ClassInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClassInfoFromCache indicates an expected call of GetClassInfoFromCache.
func (mr *MockClassInfoCacheRepoMockRecorder) GetClassInfoFromCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClassInfoFromCache", reflect.TypeOf((*MockClassInfoCacheRepo)(nil).GetClassInfoFromCache), ctx, key)
}

// SaveManyClassInfosToCache mocks base method.
func (m *MockClassInfoCacheRepo) SaveManyClassInfosToCache(ctx context.Context, keys []string, classInfos []*biz.ClassInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveManyClassInfosToCache", ctx, keys, classInfos)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveManyClassInfosToCache indicates an expected call of SaveManyClassInfosToCache.
func (mr *MockClassInfoCacheRepoMockRecorder) SaveManyClassInfosToCache(ctx, keys, classInfos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveManyClassInfosToCache", reflect.TypeOf((*MockClassInfoCacheRepo)(nil).SaveManyClassInfosToCache), ctx, keys, classInfos)
}

// UpdateClassInfoInCache mocks base method.
func (m *MockClassInfoCacheRepo) UpdateClassInfoInCache(ctx context.Context, key string, classInfo *biz.ClassInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassInfoInCache", ctx, key, classInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClassInfoInCache indicates an expected call of UpdateClassInfoInCache.
func (mr *MockClassInfoCacheRepoMockRecorder) UpdateClassInfoInCache(ctx, key, classInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassInfoInCache", reflect.TypeOf((*MockClassInfoCacheRepo)(nil).UpdateClassInfoInCache), ctx, key, classInfo)
}
