server:
  http:
    addr: 0.0.0.0:8000
    timeout: 2s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 2s
data:
  database:
    source: "root:12345678@tcp(ClassMysql:3306)/MuxiClass?charset=utf8mb4&parseTime=True&loc=Local"
  #    source: "root:12345678@tcp(127.0.0.1:13306)/MuxiClass?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: "ClassRedis:6379"
    #    addr: "127.0.0.1:16379"
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  etcd:
    addr: "Etcd:2379"
#    addr: "127.0.0.1:2379"
